-- Populando a tabela ATIVIDADES
INSERT INTO ATIVIDADE (ID, DESCRICAO) VALUES (1, 'Consultoria Financeira');
INSERT INTO ATIVIDADE (ID, DESCRICAO) VALUES (2, 'Desenvolvimento de Software');
INSERT INTO ATIVIDADE (ID, DESCRICAO) VALUES (3, 'Marketing Digital');

-- Populando a tabela CLIENTES
INSERT INTO CLIENTE (ID, NOME, CAPITAL_SOCIAL, DATA_DE_REGISTRO, ATIVIDADE_ID) VALUES (1, 'Empresa A', 100000.00, '2023-08-01', 1);
INSERT INTO CLIENTE (ID, NOME, CAPITAL_SOCIAL, DATA_DE_REGISTRO, ATIVIDADE_ID) VALUES (2, 'Empresa B', 200000.00, '2023-08-02', 2);
INSERT INTO CLIENTE (ID, NOME, CAPITAL_SOCIAL, DATA_DE_REGISTRO, ATIVIDADE_ID) VALUES (3, 'Empresa C', 300000.00, '2023-08-03', 3);
INSERT INTO CLIENTE (ID, NOME, CAPITAL_SOCIAL, DATA_DE_REGISTRO, ATIVIDADE_ID) VALUES (4, 'Empresa D', 150000.00, '2023-08-04', 1);
